language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
- pip install delegator.py toml poetry jsonschema
- python pac.py
install:
- python setup.py install
 script:
- bash autogen_test.sh

