language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
- pip install poetry
- pip install delegator.py
install:
- poetry install
script:
- python tool.py
- bash autogen_test.sh
