language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
- pip install delegator.py toml poetry jsonschema pip-tools
- python pac.py
install:
- pip-compile autogen_requirements.ini
- pip install -r requirements.txt
script:
- bash autogen_test.sh

