[tool.poetry]
name = "spain"
version = "0.1.0"

authors = [
    "spain <spain@europe.com>"
]
description = "spain"

[tool.poetry.dependencies]
python = "^3.5"
attrs = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.4"
