[tool.poetry]
name = "italy"
version = "0.1.0"

authors = [
    "italy <italy@europe.com>"
]
description = "italy"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.4"
