[package]
name = "munich"
version = "0.1.0"

[dependencies]
"europe.france" = "0.1.0"

[dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.4"

# this section stays with pr, and should be empty in the master branch
[next-version]
version = "0.1.2"
