[tool.poetry]
name = "germany"
version = "0.1.0"

authors = [
    "germany <germany@europe.com>"
]
description = "germany"

[tool.poetry.dependencies]
python = "^3.5"
Werkzeug = "0.14.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.4"
